version: '2'

services:
  wordpress:
    build: .
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - "./wp/:/var/www/html"
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db:/var/lib/mysql"
